name: Build and Release

on: 
    workflow_dispatch:
        inputs:
          version:
            description: 'Version'
            default: '1.11.0'  # Default version if not specified
jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Build and package artifacts
        run: |
          chmod +x ./compile_protoc_gen_twirp_ruby.sh  # Assuming the script is executable and correct
          ./compile_protoc_gen_twirp_ruby.sh

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          draft: true
    